name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - firstaid

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_REPOSITORY }}:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_REPOSITORY }}:latest
